let data = [
    {
        country_name: "Afghanistan",
        country_numeric_code: "4",
        country_alpha2_code: "AF",
        country_alpha3_code: "AFG",
        currency_name: "Afghani",
        currency_numeric_code: "971",
        currency_alpha3_code: "AFN",
        currency_exponent: "2",
        currency_subunit: "Pul",
        currency_description: "Afghani",
        country_tld: ".af",
        country_year_assigned: "1974"
    },
    {
        country_name: "Albania",
        country_numeric_code: "8",
        country_alpha2_code: "AL",
        country_alpha3_code: "ALB",
        currency_name: "Albanian Lek",
        currency_numeric_code: "8",
        currency_alpha3_code: "ALL",
        currency_exponent: "2",
        currency_subunit: "Qindarka",
        currency_description: "Lekë",
        country_tld: ".al",
        country_year_assigned: "1974"
    },
    {
        country_name: "Algeria",
        country_numeric_code: "12",
        country_alpha2_code: "DZ",
        country_alpha3_code: "DZA",
        currency_name: "Algerian Dinar",
        currency_numeric_code: "12",
        currency_alpha3_code: "DZD",
        currency_exponent: "2",
        currency_subunit: "Santīm",
        currency_description: "Algerian Dinars",
        country_tld: ".dz",
        country_year_assigned: "1974"
    },
    {
        country_name: "Angola",
        country_numeric_code: "24",
        country_alpha2_code: "AO",
        country_alpha3_code: "AGO",
        currency_name: "Kwanza",
        currency_numeric_code: "973",
        currency_alpha3_code: "AOA",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Kwansa",
        country_tld: ".ao",
        country_year_assigned: "1974"
    },
    {
        country_name: "Argentina",
        country_numeric_code: "32",
        country_alpha2_code: "AR",
        country_alpha3_code: "ARG",
        currency_name: "Argentine Peso",
        currency_numeric_code: "32",
        currency_alpha3_code: "ARS",
        currency_exponent: "2",
        currency_subunit: "Centavos",
        currency_description: "Argentine Pesos",
        country_tld: ".ar",
        country_year_assigned: "1974"
    },
    {
        country_name: "Armenia",
        country_numeric_code: "51",
        country_alpha2_code: "AM",
        country_alpha3_code: "ARM",
        currency_name: "Armenian Dram",
        currency_numeric_code: "51",
        currency_alpha3_code: "AMD",
        currency_exponent: "2",
        currency_subunit: "Luma",
        currency_description: "Armenian Dram",
        country_tld: ".am",
        country_year_assigned: "1992"
    },
    {
        country_name: "Aruba",
        country_numeric_code: "533",
        country_alpha2_code: "AW",
        country_alpha3_code: "ABW",
        currency_name: "Aruban Florin",
        currency_numeric_code: "533",
        currency_alpha3_code: "AWG",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Aruban Florin",
        country_tld: ".aw",
        country_year_assigned: "1986"
    },
    {
        country_name: "Australia",
        country_numeric_code: "36",
        country_alpha2_code: "AU",
        country_alpha3_code: "AUS",
        currency_name: "Australian Dollar",
        currency_numeric_code: "36",
        currency_alpha3_code: "AUD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Australian Dollars",
        country_tld: ".au",
        country_year_assigned: "1974"
    },
    {
        country_name: "Azerbaijan",
        country_numeric_code: "31",
        country_alpha2_code: "AZ",
        country_alpha3_code: "AZE",
        currency_name: "Azerbaijanian Manat",
        currency_numeric_code: "944",
        currency_alpha3_code: "AZN",
        currency_exponent: "2",
        currency_subunit: "Qəpik",
        currency_description: "Manats",
        country_tld: ".az",
        country_year_assigned: "1992"
    },
    {
        country_name: "Bahamas",
        country_numeric_code: "44",
        country_alpha2_code: "BS",
        country_alpha3_code: "BHS",
        currency_name: "Bahamian Dollar",
        currency_numeric_code: "44",
        currency_alpha3_code: "BSD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Bahamian Dollars",
        country_tld: ".bs",
        country_year_assigned: "1974"
    },
    {
        country_name: "Bahrain",
        country_numeric_code: "48",
        country_alpha2_code: "BH",
        country_alpha3_code: "BHR",
        currency_name: "Bahraini Dinar",
        currency_numeric_code: "48",
        currency_alpha3_code: "BHD",
        currency_exponent: "3",
        currency_subunit: "Fils",
        currency_description: "Bahraini Dinars",
        country_tld: ".bh",
        country_year_assigned: "1974"
    },
    {
        country_name: "Bangladesh",
        country_numeric_code: "50",
        country_alpha2_code: "BD",
        country_alpha3_code: "BGD",
        currency_name: "Bangladeshi Taka",
        currency_numeric_code: "50",
        currency_alpha3_code: "BDT",
        currency_exponent: "2",
        currency_subunit: "Poishas",
        currency_description: "Takas",
        country_tld: ".bd",
        country_year_assigned: "1974"
    },
    {
        country_name: "Barbados",
        country_numeric_code: "52",
        country_alpha2_code: "BB",
        country_alpha3_code: "BRB",
        currency_name: "Barbados Dollar",
        currency_numeric_code: "52",
        currency_alpha3_code: "BBD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Barbados Dollars",
        country_tld: ".bb",
        country_year_assigned: "1974"
    },
    {
        country_name: "Belarus",
        country_numeric_code: "112",
        country_alpha2_code: "BY",
        country_alpha3_code: "BLR",
        currency_name: "Belarussian Ruble",
        currency_numeric_code: "933",
        currency_alpha3_code: "BYR",
        currency_exponent: "2",
        currency_subunit: "Kapyeyka",
        currency_description: "Belarussian Rubles",
        country_tld: ".by",
        country_year_assigned: "1974"
    },
    {
        country_name: "Belize",
        country_numeric_code: "84",
        country_alpha2_code: "BZ",
        country_alpha3_code: "BLZ",
        currency_name: "Belize Dollar",
        currency_numeric_code: "84",
        currency_alpha3_code: "BZD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Belize Dollars",
        country_tld: ".bz",
        country_year_assigned: "1974"
    },
    {
        country_name: "Bermuda",
        country_numeric_code: "60",
        country_alpha2_code: "BM",
        country_alpha3_code: "BMU",
        currency_name: "Bermudian Dollar",
        currency_numeric_code: "60",
        currency_alpha3_code: "BMD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Bermudan Dollars",
        country_tld: ".bm",
        country_year_assigned: "1974"
    },
    {
        country_name: "Bhutan",
        country_numeric_code: "64",
        country_alpha2_code: "BT",
        country_alpha3_code: "BTN",
        currency_name: "Bhutanese Ngultrum",
        currency_numeric_code: "64",
        currency_alpha3_code: "BTN",
        currency_exponent: "2",
        currency_subunit: "Chetrums",
        currency_description: "Ngultrums",
        country_tld: ".bt",
        country_year_assigned: "1974"
    },
    {
        country_name: "Bosnia and Herzegovina",
        country_numeric_code: "70",
        country_alpha2_code: "BA",
        country_alpha3_code: "BIH",
        currency_name: "Convertible Mark",
        currency_numeric_code: "977",
        currency_alpha3_code: "BAM",
        currency_exponent: "2",
        currency_subunit: "Fenings",
        currency_description: "Convert. Marks",
        country_tld: ".ba",
        country_year_assigned: "1992"
    },
    {
        country_name: "Botswana",
        country_numeric_code: "72",
        country_alpha2_code: "BW",
        country_alpha3_code: "BWA",
        currency_name: "Botswana Pula",
        currency_numeric_code: "72",
        currency_alpha3_code: "BWP",
        currency_exponent: "2",
        currency_subunit: "Thebe",
        currency_description: "Pula",
        country_tld: ".bw",
        country_year_assigned: "1974"
    },
    {
        country_name: "Brazil",
        country_numeric_code: "76",
        country_alpha2_code: "BR",
        country_alpha3_code: "BRA",
        currency_name: "Brazilian Real",
        currency_numeric_code: "986",
        currency_alpha3_code: "BRL",
        currency_exponent: "2",
        currency_subunit: "Centavos",
        currency_description: "Brazilian Real",
        country_tld: ".br",
        country_year_assigned: "1974"
    },
    {
        country_name: "Brunei Darussalam",
        country_numeric_code: "96",
        country_alpha2_code: "BN",
        country_alpha3_code: "BRN",
        currency_name: "Brunei Dollar",
        currency_numeric_code: "96",
        currency_alpha3_code: "BND",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Brunei Dollars",
        country_tld: ".bn",
        country_year_assigned: "1974"
    },
    {
        country_name: "Bulgaria",
        country_numeric_code: "100",
        country_alpha2_code: "BG",
        country_alpha3_code: "BGR",
        currency_name: "Bulgarian Lev",
        currency_numeric_code: "975",
        currency_alpha3_code: "BGN",
        currency_exponent: "2",
        currency_subunit: "Stotinka",
        currency_description: "Lev",
        country_tld: ".bg",
        country_year_assigned: "1974"
    },
    {
        country_name: "Burundi",
        country_numeric_code: "108",
        country_alpha2_code: "BI",
        country_alpha3_code: "BDI",
        currency_name: "Burundi Franc",
        currency_numeric_code: "108",
        currency_alpha3_code: "BIF",
        currency_exponent: "0",
        currency_subunit: "Centimes",
        currency_description: "Burundi Francs",
        country_tld: ".bi",
        country_year_assigned: "1974"
    },
    {
        country_name: "Cambodia",
        country_numeric_code: "116",
        country_alpha2_code: "KH",
        country_alpha3_code: "KHM",
        currency_name: "Riel",
        currency_numeric_code: "116",
        currency_alpha3_code: "KHR",
        currency_exponent: "2",
        currency_subunit: "Sens",
        currency_description: "Riels",
        country_tld: ".kh",
        country_year_assigned: "1974"
    },
    {
        country_name: "Canada",
        country_numeric_code: "124",
        country_alpha2_code: "CA",
        country_alpha3_code: "CAN",
        currency_name: "Canadian Dollar",
        currency_numeric_code: "124",
        currency_alpha3_code: "CAD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Canadian Dollars",
        country_tld: ".ca",
        country_year_assigned: "1974"
    },
    {
        country_name: "Cape Verde",
        country_numeric_code: "132",
        country_alpha2_code: "CV",
        country_alpha3_code: "CPV",
        currency_name: "Cape Verde Escudo",
        currency_numeric_code: "132",
        currency_alpha3_code: "CVE",
        currency_exponent: "2",
        currency_subunit: "Centavos",
        currency_description: "Escudos",
        country_tld: ".cv",
        country_year_assigned: "1974"
    },
    {
        country_name: "Cayman Islands",
        country_numeric_code: "136",
        country_alpha2_code: "KY",
        country_alpha3_code: "CYM",
        currency_name: "Cayman Islands Dollar",
        currency_numeric_code: "136",
        currency_alpha3_code: "KYD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Cayman Dollars",
        country_tld: ".ky",
        country_year_assigned: "1974"
    },
    {
        country_name: "Chile",
        country_numeric_code: "152",
        country_alpha2_code: "CL",
        country_alpha3_code: "CHL",
        currency_name: "Chilean Peso",
        currency_numeric_code: "152",
        currency_alpha3_code: "CLP",
        currency_exponent: "0",
        currency_subunit: "Centavos",
        currency_description: "Chilean Pesos",
        country_tld: ".cl",
        country_year_assigned: "1974"
    },
    {
        country_name: "Chile",
        country_numeric_code: "152",
        country_alpha2_code: "CL",
        country_alpha3_code: "CHL",
        currency_name: "Unidades de Fomento",
        currency_numeric_code: "990",
        currency_alpha3_code: "CLF",
        currency_exponent: "0",
        currency_subunit: "",
        currency_description: "Unidades de Fomento",
        country_tld: ".cl",
        country_year_assigned: "1974"
    },
    {
        country_name: "China",
        country_numeric_code: "156",
        country_alpha2_code: "CN",
        country_alpha3_code: "CHN",
        currency_name: "CNH",
        currency_numeric_code: "157",
        currency_alpha3_code: "CNH",
        currency_exponent: "2",
        currency_subunit: "Fen",
        currency_description: "Yuan",
        country_tld: ".cn",
        country_year_assigned: "1974"
    },
    {
        country_name: "China",
        country_numeric_code: "156",
        country_alpha2_code: "CN",
        country_alpha3_code: "CHN",
        currency_name: "CNX",
        currency_numeric_code: "158",
        currency_alpha3_code: "CNX",
        currency_exponent: "2",
        currency_subunit: "",
        currency_description: "Cryptonex",
        country_tld: ".cn",
        country_year_assigned: "1974"
    },
    {
        country_name: "China",
        country_numeric_code: "156",
        country_alpha2_code: "CN",
        country_alpha3_code: "CHN",
        currency_name: "Yuan Renminbi",
        currency_numeric_code: "156",
        currency_alpha3_code: "CNY",
        currency_exponent: "2",
        currency_subunit: "Fen",
        currency_description: "Renminbi",
        country_tld: ".cn",
        country_year_assigned: "1974"
    },
    {
        country_name: "Colombia",
        country_numeric_code: "170",
        country_alpha2_code: "CO",
        country_alpha3_code: "COL",
        currency_name: "Colombian Peso",
        currency_numeric_code: "170",
        currency_alpha3_code: "COP",
        currency_exponent: "2",
        currency_subunit: "Centavos",
        currency_description: "Colombian Pesos",
        country_tld: ".co",
        country_year_assigned: "1974"
    },
    {
        country_name: "Comoros",
        country_numeric_code: "174",
        country_alpha2_code: "KM",
        country_alpha3_code: "COM",
        currency_name: "Comoro Franc",
        currency_numeric_code: "174",
        currency_alpha3_code: "KMF",
        currency_exponent: "0",
        currency_subunit: "Centimes",
        currency_description: "Comoro Francs",
        country_tld: ".km",
        country_year_assigned: "1974"
    },
    {
        country_name: "Costa Rica",
        country_numeric_code: "188",
        country_alpha2_code: "CR",
        country_alpha3_code: "CRI",
        currency_name: "Costa Rican Colon",
        currency_numeric_code: "188",
        currency_alpha3_code: "CRC",
        currency_exponent: "2",
        currency_subunit: "Centimos",
        currency_description: "Costa Rican Colones",
        country_tld: ".cr",
        country_year_assigned: "1974"
    },
    {
        country_name: "Croatia",
        country_numeric_code: "191",
        country_alpha2_code: "HR",
        country_alpha3_code: "HRV",
        currency_name: "Croatian Kuna",
        currency_numeric_code: "191",
        currency_alpha3_code: "HRK",
        currency_exponent: "2",
        currency_subunit: "Lipa",
        currency_description: "Kuna",
        country_tld: ".hr",
        country_year_assigned: "1992"
    },
    {
        country_name: "Cuba",
        country_numeric_code: "192",
        country_alpha2_code: "CU",
        country_alpha3_code: "CUB",
        currency_name: "Cuban Peso",
        currency_numeric_code: "192",
        currency_alpha3_code: "CUP",
        currency_exponent: "2",
        currency_subunit: "Centavos",
        currency_description: "Cuban Pesos",
        country_tld: ".cu",
        country_year_assigned: "1974"
    },
    {
        country_name: "Czech Republic",
        country_numeric_code: "203",
        country_alpha2_code: "CZ",
        country_alpha3_code: "CZE",
        currency_name: "Czech Koruna",
        currency_numeric_code: "203",
        currency_alpha3_code: "CZK",
        currency_exponent: "2",
        currency_subunit: "Haler",
        currency_description: "Korun",
        country_tld: ".cz",
        country_year_assigned: "1993"
    },
    {
        country_name: "Denmark",
        country_numeric_code: "208",
        country_alpha2_code: "DK",
        country_alpha3_code: "DNK",
        currency_name: "Danish Krone",
        currency_numeric_code: "208",
        currency_alpha3_code: "DKK",
        currency_exponent: "2",
        currency_subunit: "Ore",
        currency_description: "Danish Kroner",
        country_tld: ".dk",
        country_year_assigned: "1974"
    },
    {
        country_name: "Djibouti",
        country_numeric_code: "262",
        country_alpha2_code: "DJ",
        country_alpha3_code: "DJI",
        currency_name: "Djibouti Franc",
        currency_numeric_code: "262",
        currency_alpha3_code: "DJF",
        currency_exponent: "0",
        currency_subunit: "Centimes",
        currency_description: "Djibouti Francs",
        country_tld: ".dj",
        country_year_assigned: "1977"
    },
    {
        country_name: "Dominican Republic",
        country_numeric_code: "214",
        country_alpha2_code: "DO",
        country_alpha3_code: "DOM",
        currency_name: "Dominican Peso",
        currency_numeric_code: "214",
        currency_alpha3_code: "DOP",
        currency_exponent: "2",
        currency_subunit: "Centavos",
        currency_description: "Dominican Pesos",
        country_tld: ".do",
        country_year_assigned: "1974"
    },
    {
        country_name: "Egypt",
        country_numeric_code: "818",
        country_alpha2_code: "EG",
        country_alpha3_code: "EGY",
        currency_name: "Egyptian Pound",
        currency_numeric_code: "818",
        currency_alpha3_code: "EGP",
        currency_exponent: "2",
        currency_subunit: "Piastre",
        currency_description: "Egyptian Pounds",
        country_tld: ".eg",
        country_year_assigned: "1974"
    },
    {
        country_name: "El Salvador",
        country_numeric_code: "222",
        country_alpha2_code: "SV",
        country_alpha3_code: "SLV",
        currency_name: "El Salvador Colon",
        currency_numeric_code: "222",
        currency_alpha3_code: "SVC",
        currency_exponent: "2",
        currency_subunit: "Centavos",
        currency_description: "El Salvador Colones",
        country_tld: ".sv",
        country_year_assigned: "1974"
    },
    {
        country_name: "Ethiopia",
        country_numeric_code: "230",
        country_alpha2_code: "ET",
        country_alpha3_code: "ETH",
        currency_name: "Ethiopian Birr",
        currency_numeric_code: "230",
        currency_alpha3_code: "ETB",
        currency_exponent: "2",
        currency_subunit: "Santim",
        currency_description: "Birr",
        country_tld: ".et",
        country_year_assigned: "1974"
    },
    {
        country_name: "Falkland Islands (Malvinas)",
        country_numeric_code: "238",
        country_alpha2_code: "FK",
        country_alpha3_code: "FLK",
        currency_name: "Falkland Islands Pound",
        currency_numeric_code: "238",
        currency_alpha3_code: "FKP",
        currency_exponent: "2",
        currency_subunit: "Pence",
        currency_description: "Falkland Pounds",
        country_tld: ".fk",
        country_year_assigned: "1974"
    },
    {
        country_name: "Fiji",
        country_numeric_code: "242",
        country_alpha2_code: "FJ",
        country_alpha3_code: "FJI",
        currency_name: "Fiji Dollar",
        currency_numeric_code: "242",
        currency_alpha3_code: "FJD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Fiji Dollars",
        country_tld: ".fj",
        country_year_assigned: "1974"
    },
    {
        country_name: "Gambia",
        country_numeric_code: "270",
        country_alpha2_code: "GM",
        country_alpha3_code: "GMB",
        currency_name: "Dalasi",
        currency_numeric_code: "270",
        currency_alpha3_code: "GMD",
        currency_exponent: "2",
        currency_subunit: "Bututs",
        currency_description: "Dalasi",
        country_tld: ".gm",
        country_year_assigned: "1974"
    },
    {
        country_name: "Georgia",
        country_numeric_code: "268",
        country_alpha2_code: "GE",
        country_alpha3_code: "GEO",
        currency_name: "Lari",
        currency_numeric_code: "981",
        currency_alpha3_code: "GEL",
        currency_exponent: "2",
        currency_subunit: "Tetri",
        currency_description: "Georgian Lari",
        country_tld: ".ge",
        country_year_assigned: "1992"
    },
    {
        country_name: "Ghana",
        country_numeric_code: "288",
        country_alpha2_code: "GH",
        country_alpha3_code: "GHA",
        currency_name: "Ghana Cedi",
        currency_numeric_code: "936",
        currency_alpha3_code: "GHS",
        currency_exponent: "2",
        currency_subunit: "Pesewa",
        currency_description: "Cedis",
        country_tld: ".gh",
        country_year_assigned: "1974"
    },
    {
        country_name: "Gibraltar",
        country_numeric_code: "292",
        country_alpha2_code: "GI",
        country_alpha3_code: "GIB",
        currency_name: "Gibraltar Pound",
        currency_numeric_code: "292",
        currency_alpha3_code: "GIP",
        currency_exponent: "2",
        currency_subunit: "Pence",
        currency_description: "Gibraltar Pounds",
        country_tld: ".gi",
        country_year_assigned: "1974"
    },
    {
        country_name: "Guatemala",
        country_numeric_code: "320",
        country_alpha2_code: "GT",
        country_alpha3_code: "GTM",
        currency_name: "Quetzal",
        currency_numeric_code: "320",
        currency_alpha3_code: "GTQ",
        currency_exponent: "2",
        currency_subunit: "Centavos",
        currency_description: "Quetzales",
        country_tld: ".gt",
        country_year_assigned: "1974"
    },
    {
        country_name: "Guinea",
        country_numeric_code: "324",
        country_alpha2_code: "GN",
        country_alpha3_code: "GIN",
        currency_name: "Guinea Franc",
        currency_numeric_code: "324",
        currency_alpha3_code: "GNF",
        currency_exponent: "0",
        currency_subunit: "Centimes",
        currency_description: "Guinean Francs",
        country_tld: ".gn",
        country_year_assigned: "1974"
    },
    {
        country_name: "Guyana",
        country_numeric_code: "328",
        country_alpha2_code: "GY",
        country_alpha3_code: "GUY",
        currency_name: "Guyana Dollar",
        currency_numeric_code: "328",
        currency_alpha3_code: "GYD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Guyana Dollars",
        country_tld: ".gy",
        country_year_assigned: "1974"
    },
    {
        country_name: "Haiti",
        country_numeric_code: "332",
        country_alpha2_code: "HT",
        country_alpha3_code: "HTI",
        currency_name: "Gourde",
        currency_numeric_code: "332",
        currency_alpha3_code: "HTG",
        currency_exponent: "2",
        currency_subunit: "Centimes",
        currency_description: "Gourdes",
        country_tld: ".ht",
        country_year_assigned: "1974"
    },
    {
        country_name: "Honduras",
        country_numeric_code: "340",
        country_alpha2_code: "HN",
        country_alpha3_code: "HND",
        currency_name: "Lempira",
        currency_numeric_code: "340",
        currency_alpha3_code: "HNL",
        currency_exponent: "2",
        currency_subunit: "Centavos",
        currency_description: "Lempiras",
        country_tld: ".hn",
        country_year_assigned: "1974"
    },
    {
        country_name: "Hong Kong",
        country_numeric_code: "344",
        country_alpha2_code: "HK",
        country_alpha3_code: "HKG",
        currency_name: "Hong Kong Dollar",
        currency_numeric_code: "344",
        currency_alpha3_code: "HKD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "H.K.Dollars",
        country_tld: ".hk",
        country_year_assigned: "1974"
    },
    {
        country_name: "Hungary",
        country_numeric_code: "348",
        country_alpha2_code: "HU",
        country_alpha3_code: "HUN",
        currency_name: "Forint",
        currency_numeric_code: "348",
        currency_alpha3_code: "HUF",
        currency_exponent: "2",
        currency_subunit: "Filler",
        currency_description: "Forint",
        country_tld: ".hu",
        country_year_assigned: "1974"
    },
    {
        country_name: "Iceland",
        country_numeric_code: "352",
        country_alpha2_code: "IS",
        country_alpha3_code: "ISL",
        currency_name: "Iceland Krona",
        currency_numeric_code: "352",
        currency_alpha3_code: "ISK",
        currency_exponent: "2",
        currency_subunit: "Eyrir",
        currency_description: "Iceland Krone",
        country_tld: ".is",
        country_year_assigned: "1974"
    },
    {
        country_name: "India",
        country_numeric_code: "356",
        country_alpha2_code: "IN",
        country_alpha3_code: "IND",
        currency_name: "Indian Rupee",
        currency_numeric_code: "356",
        currency_alpha3_code: "INR",
        currency_exponent: "2",
        currency_subunit: "Paise",
        currency_description: "Indian Rupees",
        country_tld: ".in",
        country_year_assigned: "1974"
    },
    {
        country_name: "Indonesia",
        country_numeric_code: "360",
        country_alpha2_code: "ID",
        country_alpha3_code: "IDN",
        currency_name: "Rupiah",
        currency_numeric_code: "360",
        currency_alpha3_code: "IDR",
        currency_exponent: "2",
        currency_subunit: "Sen",
        currency_description: "Rupiah",
        country_tld: ".id",
        country_year_assigned: "1974"
    },
    {
        country_name: "Iraq",
        country_numeric_code: "368",
        country_alpha2_code: "IQ",
        country_alpha3_code: "IRQ",
        currency_name: "Iraqi Dinar",
        currency_numeric_code: "368",
        currency_alpha3_code: "IQD",
        currency_exponent: "3",
        currency_subunit: "Fils",
        currency_description: "Iraqi Dinars",
        country_tld: ".iq",
        country_year_assigned: "1974"
    },
    {
        country_name: "Israel",
        country_numeric_code: "376",
        country_alpha2_code: "IL",
        country_alpha3_code: "ISR",
        currency_name: "New Israeli Sheqel",
        currency_numeric_code: "376",
        currency_alpha3_code: "ILS",
        currency_exponent: "2",
        currency_subunit: "Agoras",
        currency_description: "Shekels",
        country_tld: ".il",
        country_year_assigned: "1974"
    },
    {
        country_name: "Jamaica",
        country_numeric_code: "388",
        country_alpha2_code: "JM",
        country_alpha3_code: "JAM",
        currency_name: "Jamaican Dollar",
        currency_numeric_code: "388",
        currency_alpha3_code: "JMD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Jamaican Dollars",
        country_tld: ".jm",
        country_year_assigned: "1974"
    },
    {
        country_name: "Japan",
        country_numeric_code: "392",
        country_alpha2_code: "JP",
        country_alpha3_code: "JPN",
        currency_name: "Yen",
        currency_numeric_code: "392",
        currency_alpha3_code: "JPY",
        currency_exponent: "0",
        currency_subunit: "Sen",
        currency_description: "Yen",
        country_tld: ".jp",
        country_year_assigned: "1974"
    },
    {
        country_name: "Jordan",
        country_numeric_code: "400",
        country_alpha2_code: "JO",
        country_alpha3_code: "JOR",
        currency_name: "Jordanian Dinar",
        currency_numeric_code: "400",
        currency_alpha3_code: "JOD",
        currency_exponent: "3",
        currency_subunit: "Fils",
        currency_description: "Jordanian Dinars",
        country_tld: ".jo",
        country_year_assigned: "1974"
    },
    {
        country_name: "Kazakhstan",
        country_numeric_code: "398",
        country_alpha2_code: "KZ",
        country_alpha3_code: "KAZ",
        currency_name: "Tenge",
        currency_numeric_code: "398",
        currency_alpha3_code: "KZT",
        currency_exponent: "2",
        currency_subunit: "Tiyin",
        currency_description: "Tenge",
        country_tld: ".kz",
        country_year_assigned: "1992"
    },
    {
        country_name: "Kenya",
        country_numeric_code: "404",
        country_alpha2_code: "KE",
        country_alpha3_code: "KEN",
        currency_name: "Kenyan Shilling",
        currency_numeric_code: "404",
        currency_alpha3_code: "KES",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Kenyan Shillings",
        country_tld: ".ke",
        country_year_assigned: "1974"
    },
    {
        country_name: "Kuwait",
        country_numeric_code: "414",
        country_alpha2_code: "KW",
        country_alpha3_code: "KWT",
        currency_name: "Kuwaiti Dinar",
        currency_numeric_code: "414",
        currency_alpha3_code: "KWD",
        currency_exponent: "3",
        currency_subunit: "Fils",
        currency_description: "Kuwaiti Dinars",
        country_tld: ".kw",
        country_year_assigned: "1974"
    },
    {
        country_name: "Kyrgyzstan",
        country_numeric_code: "417",
        country_alpha2_code: "KG",
        country_alpha3_code: "KGZ",
        currency_name: "Kyrgyzstan Soma",
        currency_numeric_code: "417",
        currency_alpha3_code: "KGS",
        currency_exponent: "2",
        currency_subunit: "Tyiyn",
        currency_description: "Som",
        country_tld: ".kg",
        country_year_assigned: "1992"
    },
    {
        country_name: "Lao Peoples Democratic Repub",
        country_numeric_code: "418",
        country_alpha2_code: "LA",
        country_alpha3_code: "LAO",
        currency_name: "Kip",
        currency_numeric_code: "418",
        currency_alpha3_code: "LAK",
        currency_exponent: "2",
        currency_subunit: "Att",
        currency_description: "Kip",
        country_tld: ".la",
        country_year_assigned: "1974"
    },
    {
        country_name: "Lebanon",
        country_numeric_code: "422",
        country_alpha2_code: "LB",
        country_alpha3_code: "LBN",
        currency_name: "Lebanese Pound",
        currency_numeric_code: "422",
        currency_alpha3_code: "LBP",
        currency_exponent: "2",
        currency_subunit: "Qirsh",
        currency_description: "Lebanese Pounds",
        country_tld: ".lb",
        country_year_assigned: "1974"
    },
    {
        country_name: "Lesotho",
        country_numeric_code: "426",
        country_alpha2_code: "LS",
        country_alpha3_code: "LSO",
        currency_name: "Loti",
        currency_numeric_code: "426",
        currency_alpha3_code: "LSL",
        currency_exponent: "2",
        currency_subunit: "Lisente",
        currency_description: "Maloti",
        country_tld: ".ls",
        country_year_assigned: "1974"
    },
    {
        country_name: "Liberia",
        country_numeric_code: "430",
        country_alpha2_code: "LR",
        country_alpha3_code: "LBR",
        currency_name: "Liberian Dollar",
        currency_numeric_code: "430",
        currency_alpha3_code: "LRD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Liberian Dollars",
        country_tld: ".lr",
        country_year_assigned: "1974"
    },
    {
        country_name: "Libyan Arab Jamahiriya",
        country_numeric_code: "434",
        country_alpha2_code: "LY",
        country_alpha3_code: "LBY",
        currency_name: "Libyan Dinar",
        currency_numeric_code: "434",
        currency_alpha3_code: "LYD",
        currency_exponent: "3",
        currency_subunit: "Dirhams",
        currency_description: "Libyan Dinars",
        country_tld: ".ly",
        country_year_assigned: "1974"
    },
    {
        country_name: "Macao",
        country_numeric_code: "446",
        country_alpha2_code: "MO",
        country_alpha3_code: "MAC",
        currency_name: "Pataca",
        currency_numeric_code: "446",
        currency_alpha3_code: "MOP",
        currency_exponent: "2",
        currency_subunit: "Avos",
        currency_description: "Patacas",
        country_tld: ".mo",
        country_year_assigned: "1974"
    },
    {
        country_name: "Macedonia",
        country_numeric_code: "807",
        country_alpha2_code: "MK",
        country_alpha3_code: "MKD",
        currency_name: "Denar",
        currency_numeric_code: "807",
        currency_alpha3_code: "MKD",
        currency_exponent: "2",
        currency_subunit: "Deni",
        currency_description: "Macedonian Denari",
        country_tld: ".mk",
        country_year_assigned: "1993"
    },
    {
        country_name: "Madagascar",
        country_numeric_code: "450",
        country_alpha2_code: "MG",
        country_alpha3_code: "MDG",
        currency_name: "Malagasy Ariary",
        currency_numeric_code: "969",
        currency_alpha3_code: "MGA",
        currency_exponent: "2",
        currency_subunit: "Centimes",
        currency_description: "Madagasc.Ariary",
        country_tld: ".mg",
        country_year_assigned: "1974"
    },
    {
        country_name: "Malawi",
        country_numeric_code: "454",
        country_alpha2_code: "MW",
        country_alpha3_code: "MWI",
        currency_name: "Kwacha",
        currency_numeric_code: "454",
        currency_alpha3_code: "MWK",
        currency_exponent: "2",
        currency_subunit: "Tambala",
        currency_description: "Malawi Kwacha",
        country_tld: ".mw",
        country_year_assigned: "1974"
    },
    {
        country_name: "Malaysia",
        country_numeric_code: "458",
        country_alpha2_code: "MY",
        country_alpha3_code: "MYS",
        currency_name: "Malaysian Ringgit",
        currency_numeric_code: "458",
        currency_alpha3_code: "MYR",
        currency_exponent: "2",
        currency_subunit: "Sen",
        currency_description: "Ringgit",
        country_tld: ".my",
        country_year_assigned: "1974"
    },
    {
        country_name: "Maldives",
        country_numeric_code: "462",
        country_alpha2_code: "MV",
        country_alpha3_code: "MDV",
        currency_name: "Rufiyaa",
        currency_numeric_code: "462",
        currency_alpha3_code: "MVR",
        currency_exponent: "2",
        currency_subunit: "Laari",
        currency_description: "Rufiyaa",
        country_tld: ".mv",
        country_year_assigned: "1974"
    },
    {
        country_name: "Mauritania",
        country_numeric_code: "478",
        country_alpha2_code: "MR",
        country_alpha3_code: "MRT",
        currency_name: "Ouguiya",
        currency_numeric_code: "478",
        currency_alpha3_code: "MRO",
        currency_exponent: "2",
        currency_subunit: "Khoums",
        currency_description: "Ouguiya",
        country_tld: ".mr",
        country_year_assigned: "1974"
    },
    {
        country_name: "Mauritania",
        country_numeric_code: "478",
        country_alpha2_code: "MR",
        country_alpha3_code: "MRT",
        currency_name: "Ouguiya",
        currency_numeric_code: "929",
        currency_alpha3_code: "MRU",
        currency_exponent: "2",
        currency_subunit: "khoums",
        currency_description: "Ouguiya",
        country_tld: ".mr",
        country_year_assigned: "1974"
    },
    {
        country_name: "Mauritius",
        country_numeric_code: "480",
        country_alpha2_code: "MU",
        country_alpha3_code: "MUS",
        currency_name: "Mauritius Rupee",
        currency_numeric_code: "480",
        currency_alpha3_code: "MUR",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Mauritian Rupees",
        country_tld: ".mu",
        country_year_assigned: "1974"
    },
    {
        country_name: "Mexico",
        country_numeric_code: "484",
        country_alpha2_code: "MX",
        country_alpha3_code: "MEX",
        currency_name: "Mexican Peso",
        currency_numeric_code: "484",
        currency_alpha3_code: "MXN",
        currency_exponent: "2",
        currency_subunit: "Centavos",
        currency_description: "Mexican Pesos",
        country_tld: ".mx",
        country_year_assigned: "1974"
    },
    {
        country_name: "Mongolia",
        country_numeric_code: "496",
        country_alpha2_code: "MN",
        country_alpha3_code: "MNG",
        currency_name: "Tugrik",
        currency_numeric_code: "496",
        currency_alpha3_code: "MNT",
        currency_exponent: "2",
        currency_subunit: "Mongo",
        currency_description: "Tugrik",
        country_tld: ".mn",
        country_year_assigned: "1974"
    },
    {
        country_name: "Morocco",
        country_numeric_code: "504",
        country_alpha2_code: "MA",
        country_alpha3_code: "MAR",
        currency_name: "Moroccan Dirham",
        currency_numeric_code: "504",
        currency_alpha3_code: "MAD",
        currency_exponent: "2",
        currency_subunit: "Centimes",
        currency_description: "Moroccan Dirhams",
        country_tld: ".ma",
        country_year_assigned: "1974"
    },
    {
        country_name: "Mozambique",
        country_numeric_code: "508",
        country_alpha2_code: "MZ",
        country_alpha3_code: "MOZ",
        currency_name: "Mozambique Metical",
        currency_numeric_code: "943",
        currency_alpha3_code: "MZN",
        currency_exponent: "2",
        currency_subunit: "Centavos",
        currency_description: "Meticais",
        country_tld: ".mz",
        country_year_assigned: "1974"
    },
    {
        country_name: "Myanmar",
        country_numeric_code: "104",
        country_alpha2_code: "MM",
        country_alpha3_code: "MMR",
        currency_name: "Kyat",
        currency_numeric_code: "104",
        currency_alpha3_code: "MMK",
        currency_exponent: "2",
        currency_subunit: "Pyas",
        currency_description: "Kyats",
        country_tld: ".mm",
        country_year_assigned: "1989"
    },
    {
        country_name: "Namibia",
        country_numeric_code: "516",
        country_alpha2_code: "NA",
        country_alpha3_code: "NAM",
        currency_name: "Namibia Dollar",
        currency_numeric_code: "516",
        currency_alpha3_code: "NAD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Namibian Dollars",
        country_tld: ".na",
        country_year_assigned: "1974"
    },
    {
        country_name: "Nepal",
        country_numeric_code: "524",
        country_alpha2_code: "NP",
        country_alpha3_code: "NPL",
        currency_name: "Nepalese Rupee",
        currency_numeric_code: "524",
        currency_alpha3_code: "NPR",
        currency_exponent: "2",
        currency_subunit: "Paise",
        currency_description: "Nepalese Rupees",
        country_tld: ".np",
        country_year_assigned: "1974"
    },
    {
        country_name: "New Zealand",
        country_numeric_code: "554",
        country_alpha2_code: "NZ",
        country_alpha3_code: "NZL",
        currency_name: "New Zealand Dollar",
        currency_numeric_code: "554",
        currency_alpha3_code: "NZD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "N.Zeal.Dollars",
        country_tld: ".nz",
        country_year_assigned: "1974"
    },
    {
        country_name: "Nicaragua",
        country_numeric_code: "558",
        country_alpha2_code: "NI",
        country_alpha3_code: "NIC",
        currency_name: "Cordoba Oro",
        currency_numeric_code: "558",
        currency_alpha3_code: "NIO",
        currency_exponent: "2",
        currency_subunit: "Centavos",
        currency_description: "Cordobas",
        country_tld: ".ni",
        country_year_assigned: "1974"
    },
    {
        country_name: "Nigeria",
        country_numeric_code: "566",
        country_alpha2_code: "NG",
        country_alpha3_code: "NGA",
        currency_name: "Naira",
        currency_numeric_code: "566",
        currency_alpha3_code: "NGN",
        currency_exponent: "2",
        currency_subunit: "Kobo",
        currency_description: "Naira",
        country_tld: ".ng",
        country_year_assigned: "1974"
    },
    {
        country_name: "Norway",
        country_numeric_code: "578",
        country_alpha2_code: "NO",
        country_alpha3_code: "NOR",
        currency_name: "Norwegian Krone",
        currency_numeric_code: "578",
        currency_alpha3_code: "NOK",
        currency_exponent: "2",
        currency_subunit: "Ore",
        currency_description: "Norwegian Kroner",
        country_tld: ".no",
        country_year_assigned: "1974"
    },
    {
        country_name: "Oman",
        country_numeric_code: "512",
        country_alpha2_code: "OM",
        country_alpha3_code: "OMN",
        currency_name: "Rial Omani",
        currency_numeric_code: "512",
        currency_alpha3_code: "OMR",
        currency_exponent: "3",
        currency_subunit: "Baisa",
        currency_description: "Omani Rials",
        country_tld: ".om",
        country_year_assigned: "1974"
    },
    {
        country_name: "Pakistan",
        country_numeric_code: "586",
        country_alpha2_code: "PK",
        country_alpha3_code: "PAK",
        currency_name: "Pakistan Rupee",
        currency_numeric_code: "586",
        currency_alpha3_code: "PKR",
        currency_exponent: "2",
        currency_subunit: "Paise",
        currency_description: "Pakistani Rupees",
        country_tld: ".pk",
        country_year_assigned: "1974"
    },
    {
        country_name: "Panama",
        country_numeric_code: "591",
        country_alpha2_code: "PA",
        country_alpha3_code: "PAN",
        currency_name: "Balboa",
        currency_numeric_code: "590",
        currency_alpha3_code: "PAB",
        currency_exponent: "2",
        currency_subunit: "Centesimos",
        currency_description: "Balboas",
        country_tld: ".pa",
        country_year_assigned: "1974"
    },
    {
        country_name: "Papua New Guinea",
        country_numeric_code: "598",
        country_alpha2_code: "PG",
        country_alpha3_code: "PNG",
        currency_name: "Kina",
        currency_numeric_code: "598",
        currency_alpha3_code: "PGK",
        currency_exponent: "2",
        currency_subunit: "Toea",
        currency_description: "Kina",
        country_tld: ".pg",
        country_year_assigned: "1974"
    },
    {
        country_name: "Paraguay",
        country_numeric_code: "600",
        country_alpha2_code: "PY",
        country_alpha3_code: "PRY",
        currency_name: "Guarani",
        currency_numeric_code: "600",
        currency_alpha3_code: "PYG",
        currency_exponent: "0",
        currency_subunit: "Centimos",
        currency_description: "Guaranies",
        country_tld: ".py",
        country_year_assigned: "1974"
    },
    {
        country_name: "Peru",
        country_numeric_code: "604",
        country_alpha2_code: "PE",
        country_alpha3_code: "PER",
        currency_name: "Nuevo Sol",
        currency_numeric_code: "604",
        currency_alpha3_code: "PEN",
        currency_exponent: "2",
        currency_subunit: "Centimos",
        currency_description: "Sols",
        country_tld: ".pe",
        country_year_assigned: "1974"
    },
    {
        country_name: "Philippines",
        country_numeric_code: "608",
        country_alpha2_code: "PH",
        country_alpha3_code: "PHL",
        currency_name: "Philippine Peso",
        currency_numeric_code: "608",
        currency_alpha3_code: "PHP",
        currency_exponent: "2",
        currency_subunit: "Centavos",
        currency_description: "Philippine Pesos",
        country_tld: ".ph",
        country_year_assigned: "1974"
    },
    {
        country_name: "Poland",
        country_numeric_code: "616",
        country_alpha2_code: "PL",
        country_alpha3_code: "POL",
        currency_name: "Zloty",
        currency_numeric_code: "985",
        currency_alpha3_code: "PLN",
        currency_exponent: "2",
        currency_subunit: "Grosz",
        currency_description: "Zloty",
        country_tld: ".pl",
        country_year_assigned: "1974"
    },
    {
        country_name: "Qatar",
        country_numeric_code: "634",
        country_alpha2_code: "QA",
        country_alpha3_code: "QAT",
        currency_name: "Qatari Rial",
        currency_numeric_code: "634",
        currency_alpha3_code: "QAR",
        currency_exponent: "2",
        currency_subunit: "Dirhams",
        currency_description: "Qatari Rials",
        country_tld: ".qa",
        country_year_assigned: "1974"
    },
    {
        country_name: "Republic of South Sudan",
        country_numeric_code: "728",
        country_alpha2_code: "SS",
        country_alpha3_code: "SSD",
        currency_name: "South Sudanese Pound",
        currency_numeric_code: "728",
        currency_alpha3_code: "SSP",
        currency_exponent: "2",
        currency_subunit: "Piasters",
        currency_description: "South Sudanese Pounds",
        country_tld: ".ss",
        country_year_assigned: "2011"
    },
    {
        country_name: "Romania",
        country_numeric_code: "642",
        country_alpha2_code: "RO",
        country_alpha3_code: "ROU",
        currency_name: "New Romanian Leu",
        currency_numeric_code: "946",
        currency_alpha3_code: "RON",
        currency_exponent: "2",
        currency_subunit: "Bani",
        currency_description: "Romanian Lei",
        country_tld: ".ro",
        country_year_assigned: "1974"
    },
    {
        country_name: "Russian Federation",
        country_numeric_code: "643",
        country_alpha2_code: "RU",
        country_alpha3_code: "RUS",
        currency_name: "Russian Ruble",
        currency_numeric_code: "643",
        currency_alpha3_code: "RUB",
        currency_exponent: "2",
        currency_subunit: "Kopeyka",
        currency_description: "Rubles",
        country_tld: ".ru",
        country_year_assigned: "1992"
    },
    {
        country_name: "Rwanda",
        country_numeric_code: "646",
        country_alpha2_code: "RW",
        country_alpha3_code: "RWA",
        currency_name: "Rwanda Franc",
        currency_numeric_code: "646",
        currency_alpha3_code: "RWF",
        currency_exponent: "0",
        currency_subunit: "Centimes",
        currency_description: "Rwandan Francs",
        country_tld: ".rw",
        country_year_assigned: "1974"
    },
    {
        country_name: "Saint Helena",
        country_numeric_code: "654",
        country_alpha2_code: "SH",
        country_alpha3_code: "SHN",
        currency_name: "Saint Helena Pound",
        currency_numeric_code: "654",
        currency_alpha3_code: "SHP",
        currency_exponent: "2",
        currency_subunit: "Pence",
        currency_description: "St.Helena Pounds",
        country_tld: ".sh",
        country_year_assigned: "1974"
    },
    {
        country_name: "Samoa",
        country_numeric_code: "882",
        country_alpha2_code: "WS",
        country_alpha3_code: "WSM",
        currency_name: "Tala",
        currency_numeric_code: "882",
        currency_alpha3_code: "WST",
        currency_exponent: "2",
        currency_subunit: "Sene",
        currency_description: "Tala",
        country_tld: ".ws",
        country_year_assigned: "1974"
    },
    {
        country_name: "Sao Tome and Principe",
        country_numeric_code: "678",
        country_alpha2_code: "ST",
        country_alpha3_code: "STP",
        currency_name: "Dobra",
        currency_numeric_code: "678",
        currency_alpha3_code: "STD",
        currency_exponent: "2",
        currency_subunit: "Centimos",
        currency_description: "Dobras",
        country_tld: ".st",
        country_year_assigned: "1974"
    },
    {
        country_name: "Sao Tome and Principe",
        country_numeric_code: "678",
        country_alpha2_code: "ST",
        country_alpha3_code: "STP",
        currency_name: "Dobra",
        currency_numeric_code: "930",
        currency_alpha3_code: "STN",
        currency_exponent: "2",
        currency_subunit: "Centimos",
        currency_description: "Dobra",
        country_tld: ".st",
        country_year_assigned: "1974"
    },
    {
        country_name: "Saudi Arabia",
        country_numeric_code: "682",
        country_alpha2_code: "SA",
        country_alpha3_code: "SAU",
        currency_name: "Saudi Riyal",
        currency_numeric_code: "682",
        currency_alpha3_code: "SAR",
        currency_exponent: "2",
        currency_subunit: "Halala",
        currency_description: "Saudi Riyals",
        country_tld: ".sa",
        country_year_assigned: "1974"
    },
    {
        country_name: "Serbia",
        country_numeric_code: "688",
        country_alpha2_code: "RS",
        country_alpha3_code: "SRB",
        currency_name: "Serbian Dinar",
        currency_numeric_code: "941",
        currency_alpha3_code: "RSD",
        currency_exponent: "2",
        currency_subunit: "Paras",
        currency_description: "Serbian Dinars",
        country_tld: ".rs",
        country_year_assigned: "2006"
    },
    {
        country_name: "Seychelles",
        country_numeric_code: "690",
        country_alpha2_code: "SC",
        country_alpha3_code: "SYC",
        currency_name: "Seychelles Rupee",
        currency_numeric_code: "690",
        currency_alpha3_code: "SCR",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Seychelles Rupees",
        country_tld: ".sc",
        country_year_assigned: "1974"
    },
    {
        country_name: "Sierra Leone",
        country_numeric_code: "694",
        country_alpha2_code: "SL",
        country_alpha3_code: "SLE",
        currency_name: "Leone",
        currency_numeric_code: "694",
        currency_alpha3_code: "SLL",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Leones",
        country_tld: ".sl",
        country_year_assigned: "1974"
    },
    {
        country_name: "Singapore",
        country_numeric_code: "702",
        country_alpha2_code: "SG",
        country_alpha3_code: "SGP",
        currency_name: "Singapore Dollar",
        currency_numeric_code: "702",
        currency_alpha3_code: "SGD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Singapore Dollars",
        country_tld: ".sg",
        country_year_assigned: "1974"
    },
    {
        country_name: "Solomon Islands",
        country_numeric_code: "90",
        country_alpha2_code: "SB",
        country_alpha3_code: "SLB",
        currency_name: "Solomon Islands dollar",
        currency_numeric_code: "90",
        currency_alpha3_code: "SBD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Sol.Isl.Dollars",
        country_tld: ".sb",
        country_year_assigned: "1974"
    },
    {
        country_name: "Somalia",
        country_numeric_code: "706",
        country_alpha2_code: "SO",
        country_alpha3_code: "SOM",
        currency_name: "Somali Shilling",
        currency_numeric_code: "706",
        currency_alpha3_code: "SOS",
        currency_exponent: "2",
        currency_subunit: "Senti",
        currency_description: "Somalian Shillings",
        country_tld: ".so",
        country_year_assigned: "1974"
    },
    {
        country_name: "South Africa",
        country_numeric_code: "710",
        country_alpha2_code: "ZA",
        country_alpha3_code: "ZAF",
        currency_name: "Rand",
        currency_numeric_code: "710",
        currency_alpha3_code: "ZAR",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Rand",
        country_tld: ".za",
        country_year_assigned: "1974"
    },
    {
        country_name: "Spain",
        country_numeric_code: "724",
        country_alpha2_code: "ES",
        country_alpha3_code: "ESP",
        currency_name: "ESA",
        currency_numeric_code: "996",
        currency_alpha3_code: "ESA",
        currency_exponent: "2",
        currency_subunit: "Céntimos",
        currency_description: "Bolívares Soberanos",
        country_tld: ".es",
        country_year_assigned: "1974"
    },
    {
        country_name: "Sri Lanka",
        country_numeric_code: "144",
        country_alpha2_code: "LK",
        country_alpha3_code: "LKA",
        currency_name: "Sri Lanka Rupee",
        currency_numeric_code: "144",
        currency_alpha3_code: "LKR",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Lankan Rupee",
        country_tld: ".lk",
        country_year_assigned: "1974"
    },
    {
        country_name: "Sudan",
        country_numeric_code: "729",
        country_alpha2_code: "SD",
        country_alpha3_code: "SDN",
        currency_name: "Sudanese Pound",
        currency_numeric_code: "938",
        currency_alpha3_code: "SDG",
        currency_exponent: "2",
        currency_subunit: "Qirsh (Piastre)",
        currency_description: "Sudanese Pound",
        country_tld: ".sd",
        country_year_assigned: "1974"
    },
    {
        country_name: "Suriname",
        country_numeric_code: "740",
        country_alpha2_code: "SR",
        country_alpha3_code: "SUR",
        currency_name: "Surinam Dollar",
        currency_numeric_code: "968",
        currency_alpha3_code: "SRD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Surinam Dollars",
        country_tld: ".sr",
        country_year_assigned: "1974"
    },
    {
        country_name: "Swaziland",
        country_numeric_code: "748",
        country_alpha2_code: "SZ",
        country_alpha3_code: "SWZ",
        currency_name: "Lilangeni",
        currency_numeric_code: "748",
        currency_alpha3_code: "SZL",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Lilangeni",
        country_tld: ".sz",
        country_year_assigned: "1974"
    },
    {
        country_name: "Sweden",
        country_numeric_code: "752",
        country_alpha2_code: "SE",
        country_alpha3_code: "SWE",
        currency_name: "Swedish Krona",
        currency_numeric_code: "752",
        currency_alpha3_code: "SEK",
        currency_exponent: "2",
        currency_subunit: "Ore",
        currency_description: "Swedish Kronor",
        country_tld: ".se",
        country_year_assigned: "1974"
    },
    {
        country_name: "Switzerland",
        country_numeric_code: "756",
        country_alpha2_code: "CH",
        country_alpha3_code: "CHE",
        currency_name: "Swiss Franc",
        currency_numeric_code: "756",
        currency_alpha3_code: "CHF",
        currency_exponent: "2",
        currency_subunit: "Rappen",
        currency_description: "Swiss Francs",
        country_tld: ".ch",
        country_year_assigned: "1974"
    },
    {
        country_name: "Taiwan",
        country_numeric_code: "158",
        country_alpha2_code: "TW",
        country_alpha3_code: "TWN",
        currency_name: "New Taiwan Dollar",
        currency_numeric_code: "901",
        currency_alpha3_code: "TWD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Taiwan Dollars",
        country_tld: ".tw",
        country_year_assigned: "1974"
    },
    {
        country_name: "Tajikistan",
        country_numeric_code: "762",
        country_alpha2_code: "TJ",
        country_alpha3_code: "TJK",
        currency_name: "Somoni",
        currency_numeric_code: "972",
        currency_alpha3_code: "TJS",
        currency_exponent: "2",
        currency_subunit: "Diram",
        currency_description: "Somoni",
        country_tld: ".tj",
        country_year_assigned: "1992"
    },
    {
        country_name: "Thailand",
        country_numeric_code: "764",
        country_alpha2_code: "TH",
        country_alpha3_code: "THA",
        currency_name: "Baht",
        currency_numeric_code: "764",
        currency_alpha3_code: "THB",
        currency_exponent: "2",
        currency_subunit: "Satang",
        currency_description: "Baht",
        country_tld: ".th",
        country_year_assigned: "1974"
    },
    {
        country_name: "Tonga",
        country_numeric_code: "776",
        country_alpha2_code: "TO",
        country_alpha3_code: "TON",
        currency_name: "PaÃ¢â‚¬â„¢anga",
        currency_numeric_code: "776",
        currency_alpha3_code: "TOP",
        currency_exponent: "2",
        currency_subunit: "Seniti",
        currency_description: "Paanga",
        country_tld: ".to",
        country_year_assigned: "1974"
    },
    {
        country_name: "Trinidad and Tobago",
        country_numeric_code: "780",
        country_alpha2_code: "TT",
        country_alpha3_code: "TTO",
        currency_name: "Trinidad and Tobago Dollar",
        currency_numeric_code: "780",
        currency_alpha3_code: "TTD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "Trinidad and Tobago Dollars",
        country_tld: ".tt",
        country_year_assigned: "1974"
    },
    {
        country_name: "Tunisia",
        country_numeric_code: "788",
        country_alpha2_code: "TN",
        country_alpha3_code: "TUN",
        currency_name: "Tunisian Dinar",
        currency_numeric_code: "788",
        currency_alpha3_code: "TND",
        currency_exponent: "3",
        currency_subunit: "Millimes",
        currency_description: "Tunisian Dinars",
        country_tld: ".tn",
        country_year_assigned: "1974"
    },
    {
        country_name: "Turkey",
        country_numeric_code: "792",
        country_alpha2_code: "TR",
        country_alpha3_code: "TUR",
        currency_name: "Turkish Lira",
        currency_numeric_code: "949",
        currency_alpha3_code: "TRY",
        currency_exponent: "2",
        currency_subunit: "Kurus",
        currency_description: "Lira",
        country_tld: ".tr",
        country_year_assigned: "1974"
    },
    {
        country_name: "Turkmenistan",
        country_numeric_code: "795",
        country_alpha2_code: "TM",
        country_alpha3_code: "TKM",
        currency_name: "Turkmenistan New Manat",
        currency_numeric_code: "934",
        currency_alpha3_code: "TMT",
        currency_exponent: "2",
        currency_subunit: "Tenge",
        currency_description: "Manats",
        country_tld: ".tm",
        country_year_assigned: "1992"
    },
    {
        country_name: "Uganda",
        country_numeric_code: "800",
        country_alpha2_code: "UG",
        country_alpha3_code: "UGA",
        currency_name: "Uganda Shilling",
        currency_numeric_code: "800",
        currency_alpha3_code: "UGX",
        currency_exponent: "0",
        currency_subunit: "Cents",
        currency_description: "Ugandan Shillings",
        country_tld: ".ug",
        country_year_assigned: "1974"
    },
    {
        country_name: "Ukraine",
        country_numeric_code: "804",
        country_alpha2_code: "UA",
        country_alpha3_code: "UKR",
        currency_name: "Hryvnia",
        currency_numeric_code: "980",
        currency_alpha3_code: "UAH",
        currency_exponent: "2",
        currency_subunit: "Kopiyka",
        currency_description: "Hryvnia",
        country_tld: ".ua",
        country_year_assigned: "1974"
    },
    {
        country_name: "United Arab Emirates",
        country_numeric_code: "784",
        country_alpha2_code: "AE",
        country_alpha3_code: "ARE",
        currency_name: "UAE Dirham",
        currency_numeric_code: "784",
        currency_alpha3_code: "AED",
        currency_exponent: "2",
        currency_subunit: "Fils",
        currency_description: "UAE Dirhams",
        country_tld: ".ae",
        country_year_assigned: "1974"
    },
    {
        country_name: "United Kingdom",
        country_numeric_code: "826",
        country_alpha2_code: "GB",
        country_alpha3_code: "GBR",
        currency_name: "Pound Sterling",
        currency_numeric_code: "826",
        currency_alpha3_code: "GBP",
        currency_exponent: "2",
        currency_subunit: "Pence",
        currency_description: "Pounds",
        country_tld: ".gb(.uk)",
        country_year_assigned: "1974"
    },
    {
        country_name: "United States",
        country_numeric_code: "840",
        country_alpha2_code: "US",
        country_alpha3_code: "USA",
        currency_name: "US Dollar",
        currency_numeric_code: "840",
        currency_alpha3_code: "USD",
        currency_exponent: "2",
        currency_subunit: "Cents",
        currency_description: "US Dollars",
        country_tld: ".us",
        country_year_assigned: "1974"
    },
    {
        country_name: "Uruguay",
        country_numeric_code: "858",
        country_alpha2_code: "UY",
        country_alpha3_code: "URY",
        currency_name: "Peso Uruguayo",
        currency_numeric_code: "858",
        currency_alpha3_code: "UYU",
        currency_exponent: "2",
        currency_subunit: "Centesimo",
        currency_description: "Pesos Uruguayos",
        country_tld: ".uy",
        country_year_assigned: "1974"
    },
    {
        country_name: "Uzbekistan",
        country_numeric_code: "860",
        country_alpha2_code: "UZ",
        country_alpha3_code: "UZB",
        currency_name: "Uzbekistan Sum",
        currency_numeric_code: "860",
        currency_alpha3_code: "UZS",
        currency_exponent: "2",
        currency_subunit: "Tiyin",
        currency_description: "Som",
        country_tld: ".uz",
        country_year_assigned: "1992"
    },
    {
        country_name: "Vanuatu",
        country_numeric_code: "548",
        country_alpha2_code: "VU",
        country_alpha3_code: "VUT",
        currency_name: "Vatu",
        currency_numeric_code: "548",
        currency_alpha3_code: "VUV",
        currency_exponent: "0",
        currency_subunit: "",
        currency_description: "Vatu",
        country_tld: ".vu",
        country_year_assigned: "1980"
    },
    {
        country_name: "Viet Nam",
        country_numeric_code: "704",
        country_alpha2_code: "VN",
        country_alpha3_code: "VNM",
        currency_name: "Dong",
        currency_numeric_code: "704",
        currency_alpha3_code: "VND",
        currency_exponent: "0",
        currency_subunit: "Hao",
        currency_description: "Dong",
        country_tld: ".vn",
        country_year_assigned: "1974"
    },
    {
        country_name: "Yemen",
        country_numeric_code: "886",
        country_alpha2_code: "YE",
        country_alpha3_code: "YEM",
        currency_name: "Yemeni Rial",
        currency_numeric_code: "886",
        currency_alpha3_code: "YER",
        currency_exponent: "2",
        currency_subunit: "Fils",
        currency_description: "Yemeni Rials",
        country_tld: ".ye",
        country_year_assigned: "1974"
    },
    {
        country_name: "Yemen",
        country_numeric_code: "887",
        country_alpha2_code: "YE",
        country_alpha3_code: "YE",
        currency_name: "Yemeni Rial",
        currency_numeric_code: "886",
        currency_alpha3_code: "YER",
        currency_exponent: "2",
        currency_subunit: "Fils",
        currency_description: "Yemeni Rials",
        country_tld: ".ye",
        country_year_assigned: "1974"
    },
    {
        country_name: "Zambia",
        country_numeric_code: "894",
        country_alpha2_code: "ZM",
        country_alpha3_code: "ZMB",
        currency_name: "Zambian Kwacha",
        currency_numeric_code: "967",
        currency_alpha3_code: "ZMW",
        currency_exponent: "2",
        currency_subunit: "Ngwee",
        currency_description: "Zambian Kwacha",
        country_tld: ".zm",
        country_year_assigned: "1974"
    }
]


let obj = Object.fromEntries(data.map(r=>{

    let vals = Object.values(r);

    return [r.country_alpha2_code, vals]

}))

console.log(JSON.stringify(obj))

console.log(Object.keys(data[0]))